enum UserStatus {

  ACTIVE

  INACTIVE

  BLOCKED

}



enum PatientType {

  ADULT

  CHILD

}



enum ProfessionalType {

  NURSE

  DOCTOR

  NURSING_TECHNICIAN

  PHARMACIST

  OTHER

}



enum AppointmentStatus {

  SCHEDULED

  COMPLETED

  CANCELLED

  OVERDUE

}



type User @table {

  name: String!

  birthDate: Date!

  email: String! @unique

  status: UserStatus!

  cpf: String! @unique

  sex: String

}



type Patient @table {

  user: User! @unique

  patientType: PatientType!

  responsible: Patient

}



type UBS @table {

  name: String!

  logradouro: String

  numero: String

  bairro: String

  cidade: String

  cep: String

}



type Professional @table {

  user: User! @unique

  professionalType: ProfessionalType!

  professionalRegistration: String

  ubs: UBS

}



type Vaccine @table {

  name: String!

  description: String

  requiredDoses: Int!

}



type Batch @table {

  vaccine: Vaccine!

  manufacturer: String!

  batchCode: String!

  initialQuantity: Int!

  currentQuantity: Int!

  manufacturingDate: Date

  expirationDate: Date!

}



type Appointment @table {

  patient: Patient!

  vaccine: Vaccine!

  ubs: UBS

  createdAt: Timestamp!

  scheduledAt: Timestamp!

  status: AppointmentStatus!

  notes: String

} 



type Application @table {

  patient: Patient!

  vaccine: Vaccine!

  batch: Batch

  appointment: Appointment

  professional: Professional!

  ubs: UBS!

  applicationDate: Timestamp!

  doseNumber: Int

  notes: String

}